# this R script takes variant table from GATK command VariantsToTable and generates graphs of distribution of different variant parameters

# load data specify table in the argument

#install.packages("gridExtra", lib="/storage/brno3-cerit/home/vlkofly/Rpackages/", repos="https://cran.wu.ac.at/")
#install.packages("grid", lib="/storage/brno3-cerit/home/vlkofly/Rpackages/", repos="https://cran.wu.ac.at/")


library(labeling,lib.loc="/storage/brno3-cerit/home/vlkofly/Rpackages/")
library(ggplot2,lib.loc="/storage/brno3-cerit/home/vlkofly/Rpackages/")
library(gridExtra,lib.loc="/storage/brno3-cerit/home/vlkofly/Rpackages/")
library(grid,lib.loc="/storage/brno3-cerit/home/vlkofly/Rpackages/")
library(reshape2,lib.loc="/storage/brno3-cerit/home/vlkofly/Rpackages/")
library(data.table,lib.loc="/storage/brno3-cerit/home/vlkofly/Rpackages/")

args <- commandArgs(TRUE)

inputdata <- args[1]

scf <- "scaffold_1"

print(inputdata)

basename<-gsub(".gz","",inputdata)
basename<-gsub(".vcf","",basename)
basename<-gsub(".tsv","",basename)
basename<-gsub("../","",basename)
plotname<-paste(basename,".filtering_stats.pdf",sep="")

vt <- read.table(inputdata,sep="\t", header=T) # supply the source table

#sapply(vt,mean)

ntot<-dim(vt)[1]
npass<-length(vt[vt$FILTER == "PASS",1])

print(ntot)
print(npass)

###table of filter column###
ftable <- as.data.frame(table(vt$FILTER))
names(ftable)[1]<-"FILTER values, parameters that caused variant to fail filter or PASSed"

write.table(ftable,paste(basename,"_filtering.table.tsv",sep=""), quote = FALSE, sep="\t")

#vartoplot <-c("QD","DP","MQ","FS","SOR","MQRankSum","ReadPosRankSum")
vartoplot <-c("QD","DP","MQ")
#vartoplot <-c("MQ","FS")

plotdensity<-function(var) {
	title<-paste(npass," snps passed filter (green) from total of", ntot, "snps (dashed)" ,sep=" ") # develop more this script, add some stats and so on
	p<-ggplot(vt,aes_string(x=var))+geom_density(adjust = 1/4, linetype = "dashed", alpha=0.2) + 
	geom_density(data=vt[vt$FILTER == "PASS",], mapping=aes_string(x=var),adjust=1/4,inherit.aes=FALSE,colour = "green",alpha=0.2) +
	ggtitle(title)
	#xlim(0,80)
}



pdf(plotname, onefile=TRUE)
lapply(vartoplot,plotdensity)
dev.off()

#quit(save="no")

pdf(paste(basename,".filtering_table.pdf",sep=""), height=60)
grid.newpage()
grid.table(ftable)
dev.off()

#ggplot(vt,aes(x="QUAL"))+geom_density()

##sample depth statistics
dpc<-grep(".DP",names(vt)) # get the column names for sample depths
gqc<-grep(".GQ",names(vt)) # get the column names for sample depths
dpn<-grep(".DP",names(vt),value = T) # get column values for sample depths

##function that generates mean + 2*sd depth value for each sample 
sdm<-function(x) {
  x<-na.omit(x)
  s<-sd(x)
  m<-mean(x)
  sd2<-m+2*s
  return(sd2)
}
 

sds<-sapply(vt[,dpc], sdm) # get 2sd+m per each sample, named list is generated by sapply

# loop through samples and extract possitions that have excessive depth, output into exdedsam dataframe
exdedsam<-data.frame(CHROM=character(),POS=integer(),samples=character())  
for (s in dpn) {
  sd<-paste("vt$",s,sep="")
  sd2<-sds[s]
  print(s)
  pos<-vt[eval(parse(text= sd)) > sd2,c(1,2)]
 # print(dim(pos)[1])
 # print(pos)
  pos2<-cbind(pos,"samples" = rep(s,dim(pos)[1]))
  #names(pos)
  #exded<-merge(exded,pos,by=c("CHROM","POS"),all=T)
  exdedsam<-rbind(exdedsam,pos2)
} 

exc<-data.table(exdedsam) # https://www.r-bloggers.com/efficient-aggregation-and-more-using-data-table/
excount<-exc[,list(n=length(samples)),by=list(CHROM,POS)] # this is really faster
summary(excount)
write.table(excount,paste(basename,"excess_depth_possitions_count.table.tsv",sep=""),quote=F, sep="\t")



## plot average depth of each sample

dpccp<-c(1,2,dpc) # get sample depth columns and chrom and pos

meltdp<-melt(vt[,dpccp],na.rm = T, id.vars = c(1:2)) # melt the dataset so you get table with 4 columns chr pos sample depth

names(meltdp)[c(3,4)]<-c("sample","depth")


gplothem<-theme(panel.border = element_blank(),
                axis.text.x=element_text(angle=50),
                panel.background = element_blank(),
                axis.title=element_text(size=15),
                axis.title.x=element_blank(),
                axis.line=element_line(color='black'),
                plot.title=element_text(size=17.5),
                axis.text=element_text(color='black', size=15, hjust=1, vjust=1),
                #axis.text.x=element_text(hjust=0.5),
                #text=element_text(family="serif"),
                panel.grid.major.y=element_line(size=0.5, colour='black'),
                legend.position = "none")

png(paste(basename,"_boxplot_sampledepth.png",sep=""), width=3000) # plot depth all

ggplot(data=meltdp[meltdp$CHROM == scf,],aes(y=depth,x=sample)) +
  geom_boxplot()+ # invalid graphic state?
  ggtitle(paste(basename,scf))+
  gplothem
dev.off()


png(paste(basename,"_boxplot_sampledepthmax100.png",sep=""), width=3000) # plot depth max100

ggplot(data=meltdp[meltdp$CHROM == scf,],aes(y=depth,x=sample)) +
  geom_boxplot()+ # invalid graphic state?
  ggtitle(paste(basename,scf))+
  ylim(NA,100)+
  gplothem
dev.off()


png(paste(basename,"_scatter_depth_chrom.png",sep=""), width=3000)
ggplot(data=meltdp[meltdp$CHROM == scf,],aes(y=depth,x=POS, color=sample))+
  geom_point(alpha=0.5)+
  ggtitle(paste(basename,scf))
dev.off()

#sample depth summary
dpsum<-as.data.frame(do.call(cbind,lapply(vt[,dpc],summary)))

write.table(dpsum,paste(basename,".sample.depth.summary.tsv",sep=""), quote = FALSE, sep="\t")
#sample quality summary

gqsum<-as.data.frame(do.call(cbind,lapply(vt[,gqc],summary)))
write.table(gqsum,paste(basename,".sample.quality.summary.tsv",sep=""), quote = FALSE, sep="\t")
#sample quality plot
gqccp<-c(1,2,gqc) # get sample depth columns and chrom and pos

meltdp<-melt(vt[,gqccp],na.rm = T, id.vars = c(1:2)) # melt the dataset so you get table with 4 columns chr pos sample depth

names(meltdp)[c(3,4)]<-c("sample","depth")

png(paste(basename,"_boxplot_samplequality.png",sep=""), width=3000)

ggplot(data=meltdp[meltdp$CHROM == scf,],aes(y=depth,x=sample)) +
  geom_boxplot()+ # invalid graphic state?
  ggtitle(paste(basename,scf))+
  gplothem
dev.off()

png(paste(basename,"_boxplot_samplequalitymax100.png",sep=""), width=3000)

ggplot(data=meltdp[meltdp$CHROM == scf,],aes(y=depth,x=sample)) +
  geom_boxplot()+ # invalid graphic state?
  ggtitle(paste(basename,scf))+
  ylim(NA,100)+
  gplothem
dev.off()


write.table(meltdp,paste(basename,"_molted.sample.depth.table.tsv",sep=""), quote = FALSE, sep="\t")
#write.table(excount,paste(basename,"_excess.depth.table.tsv",sep=""), quote = FALSE, sep="\t") #table where first two col are chrom and pos actual CHROM and POS is how many times this position has been found as an excessive, samples where it has been found excessive follows.
 



